// Mocks generated by Mockito 5.4.6 from annotations
// in meu_airbnb/test/features/hospedagens/dominio/usecases/hospedagem_repositorio_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:meu_airbnb/core/erros/falhas.dart' as _i5;
import 'package:meu_airbnb/features/hospedagens/dominio/entidades/hospedagem_entidade.dart'
    as _i6;
import 'package:meu_airbnb/features/hospedagens/dominio/entidades/imovel_entidade.dart'
    as _i8;
import 'package:meu_airbnb/features/hospedagens/dominio/repositorios/hospedagem_repositorio.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HospedagemRepositorio].
///
/// See the documentation for Mockito's code generation for more information.
class MockHospedagemRepositorio extends _i1.Mock
    implements _i2.HospedagemRepositorio {
  MockHospedagemRepositorio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Falha, List<_i6.HospedagemEntidade>>>
  obterTodas() =>
      (super.noSuchMethod(
            Invocation.method(#obterTodas, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Falha, List<_i6.HospedagemEntidade>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Falha, List<_i6.HospedagemEntidade>>
                  >(this, Invocation.method(#obterTodas, [])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Falha, List<_i6.HospedagemEntidade>>>);

  @override
  _i3.Future<_i4.Either<_i5.Falha, _i6.HospedagemEntidade>> adicionar(
    _i6.HospedagemEntidade? hospedagem,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#adicionar, [hospedagem]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Falha, _i6.HospedagemEntidade>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Falha, _i6.HospedagemEntidade>>(
                    this,
                    Invocation.method(#adicionar, [hospedagem]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Falha, _i6.HospedagemEntidade>>);

  @override
  _i3.Future<_i4.Either<_i5.Falha, _i6.HospedagemEntidade>> atualizar(
    _i6.HospedagemEntidade? hospedagem,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#atualizar, [hospedagem]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Falha, _i6.HospedagemEntidade>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Falha, _i6.HospedagemEntidade>>(
                    this,
                    Invocation.method(#atualizar, [hospedagem]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Falha, _i6.HospedagemEntidade>>);

  @override
  _i3.Future<_i4.Either<_i5.Falha, void>> deletar(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletar, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Falha, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Falha, void>>(
                this,
                Invocation.method(#deletar, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Falha, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Falha, List<_i8.ImovelEntidade>>> obterImoveis() =>
      (super.noSuchMethod(
            Invocation.method(#obterImoveis, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Falha, List<_i8.ImovelEntidade>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Falha, List<_i8.ImovelEntidade>>
                  >(this, Invocation.method(#obterImoveis, [])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Falha, List<_i8.ImovelEntidade>>>);
}
