// Mocks generated by Mockito 5.4.6 from annotations
// in meu_airbnb/test/features/hospedagens/presentation/stores/usecases_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:meu_airbnb/core/erros/failures.dart' as _i5;
import 'package:meu_airbnb/core/usecases/usecase.dart' as _i7;
import 'package:meu_airbnb/features/hospedagens/domain/entities/hospedagem_entity.dart'
    as _i6;
import 'package:meu_airbnb/features/hospedagens/domain/entities/imovel_entity.dart'
    as _i13;
import 'package:meu_airbnb/features/hospedagens/domain/usecases/adicionar_hospedagem.dart'
    as _i9;
import 'package:meu_airbnb/features/hospedagens/domain/usecases/atualizar_hospedagem.dart'
    as _i10;
import 'package:meu_airbnb/features/hospedagens/domain/usecases/deletar_hospedagem.dart'
    as _i11;
import 'package:meu_airbnb/features/hospedagens/domain/usecases/obter_hospedagens.dart'
    as _i2;
import 'package:meu_airbnb/features/hospedagens/domain/usecases/obter_imoveis.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ObterHospedagens].
///
/// See the documentation for Mockito's code generation for more information.
class MockObterHospedagens extends _i1.Mock implements _i2.ObterHospedagens {
  MockObterHospedagens() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.HospedagemEntity>>> call(
    _i7.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i6.HospedagemEntity>>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.Failure, List<_i6.HospedagemEntity>>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.HospedagemEntity>>>);
}

/// A class which mocks [AdicionarHospedagem].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdicionarHospedagem extends _i1.Mock
    implements _i9.AdicionarHospedagem {
  MockAdicionarHospedagem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.HospedagemEntity>> call(
    _i6.HospedagemEntity? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.HospedagemEntity>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, _i6.HospedagemEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.HospedagemEntity>>);
}

/// A class which mocks [AtualizarHospedagem].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtualizarHospedagem extends _i1.Mock
    implements _i10.AtualizarHospedagem {
  MockAtualizarHospedagem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.HospedagemEntity>> call(
    _i6.HospedagemEntity? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.HospedagemEntity>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, _i6.HospedagemEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.HospedagemEntity>>);
}

/// A class which mocks [DeletarHospedagem].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeletarHospedagem extends _i1.Mock implements _i11.DeletarHospedagem {
  MockDeletarHospedagem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(String? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [ObterImoveis].
///
/// See the documentation for Mockito's code generation for more information.
class MockObterImoveis extends _i1.Mock implements _i12.ObterImoveis {
  MockObterImoveis() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i13.ImovelEntity>>> call(
    _i7.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i13.ImovelEntity>>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.Failure, List<_i13.ImovelEntity>>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i13.ImovelEntity>>>);
}
