import 'dart:convert';

import 'package:design_system/design_system.dart';
import 'package:flutter/material.dart';
import 'package:widgetbook/widgetbook.dart';

final imagensFolder = WidgetbookFolder(
  name: 'Imagens',
  children: [
    WidgetbookComponent(
      name: 'DsImagemBase64',
      useCases: [
        WidgetbookUseCase(
          name: 'Com imagem válida',
          builder: (context) {
            // Cria um PNG válido de 1x1 pixel
            const pngBytes = [
              0x89,
              0x50,
              0x4E,
              0x47,
              0x0D,
              0x0A,
              0x1A,
              0x0A,
              0x00,
              0x00,
              0x00,
              0x0D,
              0x49,
              0x48,
              0x44,
              0x52,
              0x00,
              0x00,
              0x00,
              0x01,
              0x00,
              0x00,
              0x00,
              0x01,
              0x08,
              0x06,
              0x00,
              0x00,
              0x00,
              0x1F,
              0x15,
              0xC4,
              0x89,
              0x00,
              0x00,
              0x00,
              0x0A,
              0x49,
              0x44,
              0x41,
              0x54,
              0x08,
              0xD3,
              0x63,
              0x00,
              0x01,
              0x00,
              0x00,
              0x05,
              0x00,
              0x01,
              0x0D,
              0x0A,
              0x2D,
              0xB4,
              0x00,
              0x00,
              0x00,
              0x00,
              0x49,
              0x45,
              0x4E,
              0x44,
              0xAE,
              0x42,
              0x60,
              0x82,
            ];
            final base64 = base64Encode(pngBytes);

            return Padding(
              padding: const EdgeInsets.all(16),
              child: DsImagemBase64(
                base64: base64,
                altura: context.knobs.double.slider(
                  label: 'Altura',
                  initialValue: 150,
                  min: 50,
                  max: 300,
                ),
                largura: context.knobs.double.slider(
                  label: 'Largura',
                  initialValue: 150,
                  min: 50,
                  max: 300,
                ),
                borderRadius: context.knobs.double.slider(
                  label: 'Border Radius',
                  initialValue: 8,
                  min: 0,
                  max: 50,
                ),
              ),
            );
          },
        ),
        WidgetbookUseCase(
          name: 'Com base64 nulo',
          builder: (context) => const Padding(
            padding: EdgeInsets.all(16),
            child: DsImagemBase64(base64: null, altura: 150, largura: 150),
          ),
        ),
        WidgetbookUseCase(
          name: 'Com base64 inválido',
          builder: (context) => const Padding(
            padding: EdgeInsets.all(16),
            child: DsImagemBase64(
              base64: 'invalid-base64!!!',
              altura: 150,
              largura: 150,
            ),
          ),
        ),
        WidgetbookUseCase(
          name: 'Sem skeleton',
          builder: (context) {
            const pngBytes = [
              0x89,
              0x50,
              0x4E,
              0x47,
              0x0D,
              0x0A,
              0x1A,
              0x0A,
              0x00,
              0x00,
              0x00,
              0x0D,
              0x49,
              0x48,
              0x44,
              0x52,
              0x00,
              0x00,
              0x00,
              0x01,
              0x00,
              0x00,
              0x00,
              0x01,
              0x08,
              0x06,
              0x00,
              0x00,
              0x00,
              0x1F,
              0x15,
              0xC4,
              0x89,
              0x00,
              0x00,
              0x00,
              0x0A,
              0x49,
              0x44,
              0x41,
              0x54,
              0x08,
              0xD3,
              0x63,
              0x00,
              0x01,
              0x00,
              0x00,
              0x05,
              0x00,
              0x01,
              0x0D,
              0x0A,
              0x2D,
              0xB4,
              0x00,
              0x00,
              0x00,
              0x00,
              0x49,
              0x45,
              0x4E,
              0x44,
              0xAE,
              0x42,
              0x60,
              0x82,
            ];
            final base64 = base64Encode(pngBytes);

            return Padding(
              padding: const EdgeInsets.all(16),
              child: DsImagemBase64(
                base64: base64,
                altura: 150,
                largura: 150,
                exibirSkeleton: false,
              ),
            );
          },
        ),
        WidgetbookUseCase(
          name: 'Diferentes dimensões',
          builder: (context) {
            const pngBytes = [
              0x89,
              0x50,
              0x4E,
              0x47,
              0x0D,
              0x0A,
              0x1A,
              0x0A,
              0x00,
              0x00,
              0x00,
              0x0D,
              0x49,
              0x48,
              0x44,
              0x52,
              0x00,
              0x00,
              0x00,
              0x01,
              0x00,
              0x00,
              0x00,
              0x01,
              0x08,
              0x06,
              0x00,
              0x00,
              0x00,
              0x1F,
              0x15,
              0xC4,
              0x89,
              0x00,
              0x00,
              0x00,
              0x0A,
              0x49,
              0x44,
              0x41,
              0x54,
              0x08,
              0xD3,
              0x63,
              0x00,
              0x01,
              0x00,
              0x00,
              0x05,
              0x00,
              0x01,
              0x0D,
              0x0A,
              0x2D,
              0xB4,
              0x00,
              0x00,
              0x00,
              0x00,
              0x49,
              0x45,
              0x4E,
              0x44,
              0xAE,
              0x42,
              0x60,
              0x82,
            ];
            final base64 = base64Encode(pngBytes);

            return Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                children: [
                  DsImagemBase64(base64: base64, altura: 100, largura: 100),
                  const SizedBox(height: 16),
                  DsImagemBase64(base64: base64, altura: 150, largura: 250),
                  const SizedBox(height: 16),
                  DsImagemBase64(
                    base64: base64,
                    altura: 200,
                    largura: double.infinity,
                    borderRadius: 16,
                  ),
                ],
              ),
            );
          },
        ),
      ],
    ),
  ],
);
