// Mocks generated by Mockito 5.4.6 from annotations
// in meu_airbnb/test/features/hospedagens/data/repositories/datasource_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:meu_airbnb/features/hospedagens/data/datasources/hospedagem_local_datasource.dart'
    as _i3;
import 'package:meu_airbnb/features/hospedagens/domain/entities/hospedagem_entity.dart'
    as _i2;
import 'package:meu_airbnb/features/hospedagens/domain/entities/imovel_entity.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHospedagemEntity_0 extends _i1.SmartFake
    implements _i2.HospedagemEntity {
  _FakeHospedagemEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HospedagemLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHospedagemLocalDataSource extends _i1.Mock
    implements _i3.HospedagemLocalDataSource {
  MockHospedagemLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> inicializar() =>
      (super.noSuchMethod(
            Invocation.method(#inicializar, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.HospedagemEntity>> obterTodas() =>
      (super.noSuchMethod(
            Invocation.method(#obterTodas, []),
            returnValue: _i4.Future<List<_i2.HospedagemEntity>>.value(
              <_i2.HospedagemEntity>[],
            ),
          )
          as _i4.Future<List<_i2.HospedagemEntity>>);

  @override
  _i4.Future<_i2.HospedagemEntity> adicionar(
    _i2.HospedagemEntity? hospedagem,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#adicionar, [hospedagem]),
            returnValue: _i4.Future<_i2.HospedagemEntity>.value(
              _FakeHospedagemEntity_0(
                this,
                Invocation.method(#adicionar, [hospedagem]),
              ),
            ),
          )
          as _i4.Future<_i2.HospedagemEntity>);

  @override
  _i4.Future<_i2.HospedagemEntity> atualizar(
    _i2.HospedagemEntity? hospedagem,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#atualizar, [hospedagem]),
            returnValue: _i4.Future<_i2.HospedagemEntity>.value(
              _FakeHospedagemEntity_0(
                this,
                Invocation.method(#atualizar, [hospedagem]),
              ),
            ),
          )
          as _i4.Future<_i2.HospedagemEntity>);

  @override
  _i4.Future<void> deletar(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletar, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.ImovelEntity>> obterImoveis() =>
      (super.noSuchMethod(
            Invocation.method(#obterImoveis, []),
            returnValue: _i4.Future<List<_i5.ImovelEntity>>.value(
              <_i5.ImovelEntity>[],
            ),
          )
          as _i4.Future<List<_i5.ImovelEntity>>);
}
